# Writes the compiled shaders into a C++ table that links into the executables.
# Run with cmake -P, passing -DOUTPUT_FILE=<source to write> and -DLIST_FILE=<one shader path per line>.
# Without LIST_FILE the table is empty, which suits the D3D8 backend.

set(shader_names "")
if(LIST_FILE)
    file(STRINGS "${LIST_FILE}" shader_paths)
    foreach(path ${shader_paths})
        get_filename_component(name "${path}" NAME)
        string(TOLOWER "${name}" name)
        list(APPEND shader_names "${name}")
        set("shader_path_${name}" "${path}")
    endforeach()
endif()

# Find_Embedded_Shader binary searches, so the names stay lowercase and sorted bytewise.
list(SORT shader_names)

# Sixteen bytes to a line keeps MSVC well inside its line limits.
string(REPEAT "[0-9a-f]" 32 line_pattern)

set(blobs "")
set(entries "")
set(index 0)
foreach(name ${shader_names})
    file(READ "${shader_path_${name}}" hex HEX)
    string(LENGTH "${hex}" length)
    math(EXPR size "${length} / 2")
    string(REGEX REPLACE "(${line_pattern})" "\\1\n" hex "${hex}")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
    string(APPEND blobs "static const union { unsigned char bytes[${size}]; DWORD align; } s_shader${index} = { {\n${hex}\n} };\n\n")
    string(APPEND entries "\t{ \"shaders\\\\${name}\", s_shader${index}.bytes, ${size} },\n")
    math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUTPUT_FILE}"
"// Generated by cmake/embed_shaders.cmake from the compiled shaders. Do not edit.

#include \"W3DDevice/GameClient/W3DEmbeddedShaders.h\"

// Each blob shares a union with a DWORD so Direct3D reads its tokens aligned.
${blobs}const EmbeddedShader TheEmbeddedShaders[] =
{
${entries}\t{ 0, 0, 0 }
};

const unsigned int TheEmbeddedShaderCount = ${index};
")
